
development:
   adapter: postgresql
   encoding: unicode
   database: vittorana
   username: postgres
   password: postgres

test:
   adapter: postgresql
   encoding: unicode
   database: vittorana
   username: postgres
   password: postgres

production:
   adapter: postgresql
   encoding: unicode
   database: vittorana
   username: postgres
   password: postgres
