development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
   adapter: postgresql
   encoding: unicode
   database: vittorana
   username: postgres
   password: postgres
   host: localhost

production:
   adapter: postgresql
   encoding: unicode
   database: vittorana
   username: postgres
   password: postgres
   host: localhost

