# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf48289aceb28d356afc1cec252b5a3b378e69a71dab7363a6f8e81f27281a5fbc235ffeb43306d28f5bf5a9cb9d456849a5581d8a58c3467a06c7103e5c21c4

test:
  secret_key_base: e5245efdf0a6d3d5df71fa72e6a20ae9d90df1cb5646aa8c9377ef4a4653ee4018bdd81f9ab48f0cc8cb8ca6e81264561f5bada9bff618437ae9bace30b35e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
